---
title: "Aging Signatures EDA"
author: "Andrew Chen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: 'united'
    toc: true
    toc_depth: 1
    kee_md: yes
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r, echo=FALSE, include=FALSE}
library(tidyverse)
library(GSA)
library(babelgene)
PATH <- file.path(Sys.getenv("MLAB"), file.path("projects/brcameta/projects/sig_recon"))
```

```{r}
gmt_data <- GSA.read.gmt(file.path(PATH, "data/sigs/aging/m8.all.v2024.1.Mm.symbols.gmt"))
geneset_list <- setNames(gmt_data$genesets, gmt_data$geneset.names)
geneset_list <- geneset_list[grep("TABULA_MURIS_SENIS", names(geneset_list))]
```

```{r}
geneset_list %>% names
```
```{r}
geneset_human_list <- lapply(geneset_list, function(x) babelgene::orthologs(x, species = "mouse", human = FALSE)[["human_symbol"]])
```


```{r}
saveRDS(geneset_list, file.path(PATH, "data/sigs/aging/tabula_muris_senis_sigs_m.rds"))
saveRDS(geneset_human_list, file.path(PATH, "data/sigs/aging/tabula_muris_senis_sigs_h.rds"))
```

