---
title: "DrugMatrix - Baselines"
author: "Andrew Chen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: 'united'
    toc: true
    toc_depth: 1
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(sigrecon)
library(SummarizedExperiment)
library(Biobase)
library(doParallel)
PROJECT_PATH <- file.path(Sys.getenv("MLAB"), "projects/brcameta/projects/sig_recon/")
DATAPATH <- file.path(Sys.getenv("MLAB"), "projects/brcameta/projects/sig_recon/data/sigs/drugmatrix")
do_save <- FALSE
```

```{r}
#True Sig
kidney_true_sig <- sigrecon::drugmatrix.kidney
kidney_true_sig_up <- lapply(kidney_true_sig, function(x) x$up)
liver_true_sig <- sigrecon::drugmatrix.liver
liver_true_sig_up <- lapply(liver_true_sig, function(x) x$up)
```

# No Change

```{r}
if(do_save) {
  liver_recon_eval_table <- sig_eval_table(source_sigs = liver_true_sig_up,
                                         pred_sigs = liver_true_sig_up, 
                                         true_sigs = kidney_true_sig)
  liver_recon_eval_table$source <- "liver"
  kidney_recon_eval_table <- sig_eval_table(source_sigs = kidney_true_sig_up,
                                         pred_sigs = kidney_true_sig_up, 
                                         true_sigs = liver_true_sig)
  kidney_recon_eval_table$source <- "kidney"
  no_change_df <- rbind(liver_recon_eval_table, kidney_recon_eval_table)

  saveRDS(no_change_df, file.path(PROJECT_PATH, "results/eval/drugmatrix/no_change_eval_table.rds"))
} else {
  no_change_df <- readRDS(file.path(PROJECT_PATH, "results/eval/drugmatrix/no_change_eval_table.rds"))
}

no_change_path <- file.path(PROJECT_PATH, "results/eval/drugmatrix/no_change_eval_table.rds")
```

```{r}
no_change_df %>% 
  dplyr::group_by(source) %>%
  summarize(NES_mean = mean(NES),
            jacc = mean(jacc))
```

```{r}
no_change_df %>% 
  dplyr::group_by(source) %>%
  summarize(NES = mean(NES),
            jacc = mean(jacc)) %>%
  summarize(NES_mean = mean(NES),
            jacc_mean = mean(jacc))
```

# Mean {.tabset}

## Control {.tabset}
```{r}
#Pred Sig
liver_sig <- readRDS(file.path(DATAPATH, "mean/ctrl/liver_ctrl.rds"))
kidney_sig <- readRDS(file.path(DATAPATH, "mean/ctrl/kidney_ctrl.rds"))
kidney_pred_sig <- rep(list(kidney_sig[["up"]]), length(kidney_true_sig))
names(kidney_pred_sig) <- names(kidney_true_sig)
liver_pred_sig <- rep(list(liver_sig[["up"]]), length(liver_true_sig))
names(liver_pred_sig) <- names(liver_true_sig)
```

```{r}
if(do_save) {
  liver_recon_eval_table <- sig_eval_table(source_sigs = liver_true_sig_up,
                                           pred_sigs = kidney_pred_sig, 
                                           true_sigs = kidney_true_sig,
                                           source = "liver",
                                           target = "kidney")
  kidney_recon_eval_table <- sig_eval_table(source_sigs = kidney_true_sig_up,
                                            pred_sigs = liver_pred_sig, 
                                            true_sigs = liver_true_sig,
                                            source = "kidney",
                                            target = "liver")

  change_df <- rbind(liver_recon_eval_table,
                     kidney_recon_eval_table)
  saveRDS(change_df, file.path(PROJECT_PATH, "results/eval/drugmatrix/ctrl_mean_eval_table.rds"))
} else {
  change_df <- readRDS(file.path(PROJECT_PATH, "results/eval/drugmatrix/ctrl_mean_eval_table.rds"))
}

```

### Unpaired
```{r}
change_df %>% 
  dplyr::group_by(source) %>%
  summarize(NES_mean = mean(NES),
            jacc = mean(jacc))
```

```{r}
change_df %>% 
  dplyr::group_by(source) %>%
  summarize(NES = mean(NES),
            jacc = mean(jacc)) %>%
  summarize(NES_mean = mean(NES),
            jacc_mean = mean(jacc))
```

### Paired
```{r}
combined_aggregated_df <- paired_eval_table(change_df, no_change_path)
```

```{r}
combined_aggregated_df %>% 
  group_by(source) %>% 
  summarize(Jacc_Wilcox_pval = wilcox.test(jacc_TRUE, jacc_FALSE, paired = TRUE, alternative="greater")$p.value,
            NES_Wilcox_pval = wilcox.test(NES_TRUE, NES_FALSE, paired = TRUE, alternative="greater")$p.value) %>%
  summarize(NES_meta_p = fishers_meta_p(NES_Wilcox_pval),
            Jacc_meta_p = fishers_meta_p(Jacc_Wilcox_pval))
```

## 1/10 {.tabset}
```{r}
#Pred Sig
liver_sig <- readRDS(file.path(DATAPATH, "mean/10th_perturb/liver_10_signatures.rds"))
kidney_sig <- readRDS(file.path(DATAPATH, "mean/10th_perturb/kidney_10_signatures.rds"))
kidney_pred_sig <- list()
for(split in 1:length(kidney_sig)) {
  kidney_pred_sig[[split]] <- rep(list(kidney_sig[[split]][["up"]]), length(kidney_true_sig))
  names(kidney_pred_sig[[split]]) <- names(kidney_true_sig)  
}
names(kidney_pred_sig) <- paste0("split_", 1:10)
liver_pred_sig <- list()
for(split in 1:length(kidney_sig)) {
  liver_pred_sig[[split]] <- rep(list(liver_sig[[split]][["up"]]), length(liver_true_sig))
  names(liver_pred_sig[[split]]) <- names(liver_true_sig)  
}
names(liver_pred_sig) <- paste0("split_", 1:10)
```

```{r}
if(do_save) {
  liver_recon_eval_table <- sig_eval_table(source_sigs = liver_true_sig_up,
                                           pred_sigs = kidney_pred_sig, 
                                           true_sigs = kidney_true_sig,
                                           source = "liver",
                                           target = "kidney",
                                           splits = TRUE,
                                           split_file = file.path(PROJECT_PATH, "data/sigs/drugmatrix/drug_splits.csv"),
                                           split_pb_col = "drug",
                                           split_type = "10th")
kidney_recon_eval_table <- sig_eval_table(source_sigs = kidney_true_sig_up,
                                          pred_sigs = liver_pred_sig, 
                                          true_sigs = liver_true_sig,
                                          source = "kidney",
                                          target = "liver",
                                          splits = TRUE,
                                          split_file = file.path(PROJECT_PATH, "data/sigs/drugmatrix/drug_splits.csv"),
                                           split_pb_col = "drug",
                                           split_type = "10th")

  change_df <- rbind(liver_recon_eval_table,
                     kidney_recon_eval_table)
  saveRDS(change_df, file.path(PROJECT_PATH, "results/eval/drugmatrix/ctrl_10th_mean_eval_table.rds"))
} else {
  change_df <- readRDS(file.path(PROJECT_PATH, "results/eval/drugmatrix/ctrl_10th_mean_eval_table.rds"))
}

```

### Unpaired
```{r}
change_df %>% 
  dplyr::group_by(source) %>%
  summarize(NES_mean = mean(NES),
            jacc = mean(jacc))
```

```{r}
change_df %>% 
  dplyr::group_by(source) %>%
  summarize(NES = mean(NES),
            jacc = mean(jacc)) %>%
  summarize(NES_mean = mean(NES),
            jacc_mean = mean(jacc))
```

### Paired
```{r}
combined_aggregated_df <- paired_eval_table(change_df, no_change_path)
```

```{r}
combined_aggregated_df %>% 
  group_by(source) %>% 
  summarize(Jacc_Wilcox_pval = wilcox.test(jacc_TRUE, jacc_FALSE, paired = TRUE, alternative="greater")$p.value,
            NES_Wilcox_pval = wilcox.test(NES_TRUE, NES_FALSE, paired = TRUE, alternative="greater")$p.value) %>%
  summarize(NES_meta_p = fishers_meta_p(NES_Wilcox_pval),
            Jacc_meta_p = fishers_meta_p(Jacc_Wilcox_pval))
```

## 9/10 {.tabset}
```{r}
#Pred Sig
liver_sig <- readRDS(file.path(DATAPATH, "mean/90th_perturb/liver_90_signatures.rds"))
kidney_sig <- readRDS(file.path(DATAPATH, "mean/90th_perturb/kidney_90_signatures.rds"))
kidney_pred_sig <- list()
for(split in 1:length(kidney_sig)) {
  kidney_pred_sig[[split]] <- rep(list(kidney_sig[[split]][["up"]]), length(kidney_true_sig))
  names(kidney_pred_sig[[split]]) <- names(kidney_true_sig)  
}
names(kidney_pred_sig) <- paste0("split_", 1:10)
liver_pred_sig <- list()
for(split in 1:length(kidney_sig)) {
  liver_pred_sig[[split]] <- rep(list(liver_sig[[split]][["up"]]), length(liver_true_sig))
  names(liver_pred_sig[[split]]) <- names(liver_true_sig)  
}
names(liver_pred_sig) <- paste0("split_", 1:10)

```

```{r}
if(do_save) {
  liver_recon_eval_table <- sig_eval_table(source_sigs = liver_true_sig_up,
                                           pred_sigs = kidney_pred_sig, 
                                           true_sigs = kidney_true_sig,
                                           source = "liver",
                                           target = "kidney",
                                           splits = TRUE,
                                           split_file = file.path(PROJECT_PATH, "data/sigs/drugmatrix/drug_splits.csv"),
                                           split_pb_col = "drug",
                                           split_type = "90th")
kidney_recon_eval_table <- sig_eval_table(source_sigs = kidney_true_sig_up,
                                          pred_sigs = liver_pred_sig, 
                                          true_sigs = liver_true_sig,
                                          source = "kidney",
                                          target = "liver",
                                          splits = TRUE,
                                          split_file = file.path(PROJECT_PATH, "data/sigs/drugmatrix/drug_splits.csv"),
                                           split_pb_col = "drug",
                                           split_type = "90th")

  change_df <- rbind(liver_recon_eval_table,
                     kidney_recon_eval_table)
  saveRDS(change_df, file.path(PROJECT_PATH, "results/eval/drugmatrix/ctrl_90th_mean_eval_table.rds"))
} else {
  change_df <- readRDS(file.path(PROJECT_PATH, "results/eval/drugmatrix/ctrl_90th_mean_eval_table.rds"))
}
```

### Unpaired
```{r}
change_df %>% 
  dplyr::group_by(source) %>%
  summarize(NES_mean = mean(NES),
            jacc = mean(jacc))
```

```{r}
change_df %>% 
  dplyr::group_by(source) %>%
  summarize(NES = mean(NES),
            jacc = mean(jacc)) %>%
  summarize(NES_mean = mean(NES),
            jacc_mean = mean(jacc))
```

### Paired
```{r}
combined_aggregated_df <- paired_eval_table(change_df, no_change_path)
```

```{r}
combined_aggregated_df %>% 
  group_by(source) %>% 
  summarize(Jacc_Wilcox_pval = wilcox.test(jacc_TRUE, jacc_FALSE, paired = TRUE, alternative="greater")$p.value,
            NES_Wilcox_pval = wilcox.test(NES_TRUE, NES_FALSE, paired = TRUE, alternative="greater")$p.value) %>%
  summarize(NES_meta_p = fishers_meta_p(NES_Wilcox_pval),
            Jacc_meta_p = fishers_meta_p(Jacc_Wilcox_pval))
```

## Plots {.tabset}

### NCI H23 to A498
```{r}
combined_aggregated_df %>% 
  filter(source=="kidney") %>%
  filter(target=="liver") %>%
  ggplot(aes(x=NES_FALSE, y=NES_TRUE)) +
  geom_point(aes(alpha=kept_alpha)) +
  geom_abline(color="black") +
  scale_alpha_continuous("Proportion of Source Kept") +
  labs(title = paste("NES Scores in", "kidney Up"), 
       x = "NES Score (Before)",
       y = "NES Score (After)")
```