---
title: "GSVA Recontextualization"
author: "Andrew Chen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: 'united'
    toc: true
    toc_depth: 1
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r, echo=FALSE}
library(tidyverse)
library(sigrecon)
library(Seurat)
library(SingleCellExperiment)

PATH <- file.path(Sys.getenv("MLAB"), "projects/brcameta/projects/sig_recon")
DATA_PATH <- file.path(Sys.getenv("CBM"), "sci-plex")
```
# Loading Data
```{r}
# Load signatures
a549_sigs <- sigrecon::sciplex.a549
k562_sigs <- sigrecon::sciplex.k562
mcf7_sigs <- sigrecon::sciplex.mcf7

a549_sigs_up <- lapply(a549_sigs, function(x) x$up)
k562_sigs_up <- lapply(k562_sigs, function(x) x$up)
mcf7_sigs_up <- lapply(mcf7_sigs, function(x) x$up)

# Loading Sci-Plex Data
a549 <- readRDS(file.path(DATA_PATH, "a549.rds"))
k562 <- readRDS(file.path(DATA_PATH, "k562.rds"))
mcf7 <- readRDS(file.path(DATA_PATH, "mcf7.rds"))
a549[["RNA"]]$counts <- LayerData(a549, assay = "RNA", layer = "data")
a549[["RNA"]]$data <- NULL
k562[["RNA"]]$counts <- LayerData(k562, assay = "RNA", layer = "data")
k562[["RNA"]]$data <- NULL
mcf7[["RNA"]]$counts <- LayerData(mcf7, assay = "RNA", layer = "data")
mcf7[["RNA"]]$data <- NULL

a549 <- NormalizeData(a549)
k562 <- NormalizeData(k562)
mcf7 <- NormalizeData(mcf7)

# All profiles SCE
a549_pb <- readRDS(file.path(DATA_PATH, "a549_pb.rds"))
k562_pb <- readRDS(file.path(DATA_PATH, "k562_pb.rds"))
mcf7_pb <- readRDS(file.path(DATA_PATH, "mcf7_pb.rds"))

a549_pb <- FindVariableFeatures(a549_pb, nfeatures = 7500)
k562_pb <- FindVariableFeatures(k562_pb, nfeatures = 7500)
mcf7_pb <- FindVariableFeatures(mcf7_pb, nfeatures = 7500)

a549_var_genes <- VariableFeatures(a549_pb)
k562_var_genes <- VariableFeatures(k562_pb)
mcf7_var_genes <- VariableFeatures(mcf7_pb)

a549_all_sce <- as.SingleCellExperiment(a549_pb[VariableFeatures(a549_pb),])
k562_all_sce <- as.SingleCellExperiment(k562_pb[VariableFeatures(k562_pb),])
mcf7_all_sce <- as.SingleCellExperiment(mcf7_pb[VariableFeatures(mcf7_pb),])

# Control profiles SCE
a549_control <- subset(a549, subset = vehicle == TRUE)
k562_control <- subset(k562, subset = vehicle == TRUE)
mcf7_control <- subset(mcf7, subset = vehicle == TRUE)

a549_control <- Seurat::AggregateExpression(a549_control, group.by = "pcr_well", return.seurat = TRUE)
k562_control <- Seurat::AggregateExpression(k562_control, group.by = "pcr_well", return.seurat = TRUE)
mcf7_control <- Seurat::AggregateExpression(mcf7_control, group.by = "pcr_well", return.seurat = TRUE)

a549_control <- FindVariableFeatures(a549_control, nfeatures = 5000)
k562_control <- FindVariableFeatures(k562_control, nfeatures = 5000)
mcf7_control <- FindVariableFeatures(mcf7_control, nfeatures = 5000)

a549_var_genes <- VariableFeatures(a549_control)
k562_var_genes <- VariableFeatures(k562_control)
mcf7_var_genes <- VariableFeatures(mcf7_control)

a549_control_sce <- as.SingleCellExperiment(a549_control[VariableFeatures(a549_control),])
k562_control_sce <- as.SingleCellExperiment(k562_control[VariableFeatures(k562_control),])
mcf7_control_sce <- as.SingleCellExperiment(mcf7_control[VariableFeatures(mcf7_control),])

# Perturbed profiles
a549_perturb <- a549_pb[,!str_detect(a549_pb$pb_id, "Vehicle-0"),]
k562_perturb <- k562_pb[,!str_detect(k562_pb$pb_id, "Vehicle-0"),]
mcf7_perturb <- mcf7_pb[,!str_detect(mcf7_pb$pb_id, "Vehicle-0"),]

a549_perturb <- FindVariableFeatures(a549_perturb, nfeatures = 5000)
k562_perturb <- FindVariableFeatures(k562_perturb, nfeatures = 5000)
mcf7_perturb <- FindVariableFeatures(mcf7_perturb, nfeatures = 5000)

a549_var_genes <- VariableFeatures(a549_perturb)
k562_var_genes <- VariableFeatures(k562_perturb)
mcf7_var_genes <- VariableFeatures(mcf7_perturb)

a549_perturb_sce <- as.SingleCellExperiment(a549_perturb[VariableFeatures(a549_perturb),])
k562_perturb_sce <- as.SingleCellExperiment(k562_perturb[VariableFeatures(k562_perturb),])
mcf7_perturb_sce <- as.SingleCellExperiment(mcf7_perturb[VariableFeatures(mcf7_perturb),])
```

# GSVA
```{r}
a549_k562_recon_all_sigs <- gsva_recon(a549_all_sce, k562_sigs_up)
a549_mcf7_recon_all_sigs <- gsva_recon(a549_all_sce, mcf7_sigs_up)
k562_a549_recon_all_sigs <- gsva_recon(k562_all_sce, a549_sigs_up)
k562_mcf7_recon_all_sigs <- gsva_recon(k562_all_sce, mcf7_sigs_up)
mcf7_a549_recon_all_sigs <- gsva_recon(mcf7_all_sce, a549_sigs_up)
mcf7_k562_recon_all_sigs <- gsva_recon(mcf7_all_sce, k562_sigs_up)

a549_k562_recon_control_sigs <- gsva_recon(a549_control_sce, k562_sigs_up)
a549_mcf7_recon_control_sigs <- gsva_recon(a549_control_sce, mcf7_sigs_up)
k562_a549_recon_control_sigs <- gsva_recon(k562_control_sce, a549_sigs_up)
k562_mcf7_recon_control_sigs <- gsva_recon(k562_control_sce, mcf7_sigs_up)
mcf7_a549_recon_control_sigs <- gsva_recon(mcf7_control_sce, a549_sigs_up)
mcf7_k562_recon_control_sigs <- gsva_recon(mcf7_control_sce, k562_sigs_up)

a549_k562_recon_perturb_sigs <- gsva_recon(a549_perturb_sce, k562_sigs_up)
a549_mcf7_recon_perturb_sigs <- gsva_recon(a549_perturb_sce, mcf7_sigs_up)
k562_a549_recon_perturb_sigs <- gsva_recon(k562_perturb_sce, a549_sigs_up)
k562_mcf7_recon_perturb_sigs <- gsva_recon(k562_perturb_sce, mcf7_sigs_up)
mcf7_a549_recon_perturb_sigs <- gsva_recon(mcf7_perturb_sce, a549_sigs_up)
mcf7_k562_recon_perturb_sigs <- gsva_recon(mcf7_perturb_sce, k562_sigs_up)

saveRDS(a549_k562_recon_all_sigs, file.path(PATH, "data/sigs/sciplex/recon/a549_k562_gsva_recon_all.rds"))
saveRDS(a549_mcf7_recon_all_sigs, file.path(PATH, "data/sigs/sciplex/recon/a549_mcf7_gsva_recon_all.rds"))
saveRDS(k562_a549_recon_all_sigs, file.path(PATH, "data/sigs/sciplex/recon/k562_a549_gsva_recon_all.rds"))
saveRDS(k562_mcf7_recon_all_sigs, file.path(PATH, "data/sigs/sciplex/recon/k562_mcf7_gsva_recon_all.rds"))
saveRDS(mcf7_a549_recon_all_sigs, file.path(PATH, "data/sigs/sciplex/recon/mcf7_a549_gsva_recon_all.rds"))
saveRDS(mcf7_k562_recon_all_sigs, file.path(PATH, "data/sigs/sciplex/recon/mcf7_k562_gsva_recon_all.rds"))

saveRDS(a549_k562_recon_control_sigs, file.path(PATH, "data/sigs/sciplex/recon/a549_k562_gsva_recon_control.rds"))
saveRDS(a549_mcf7_recon_control_sigs, file.path(PATH, "data/sigs/sciplex/recon/a549_mcf7_gsva_recon_control.rds"))
saveRDS(k562_a549_recon_control_sigs, file.path(PATH, "data/sigs/sciplex/recon/k562_a549_gsva_recon_control.rds"))
saveRDS(k562_mcf7_recon_control_sigs, file.path(PATH, "data/sigs/sciplex/recon/k562_mcf7_gsva_recon_control.rds"))
saveRDS(mcf7_a549_recon_control_sigs, file.path(PATH, "data/sigs/sciplex/recon/mcf7_a549_gsva_recon_control.rds"))
saveRDS(mcf7_k562_recon_control_sigs, file.path(PATH, "data/sigs/sciplex/recon/mcf7_k562_gsva_recon_control.rds"))

saveRDS(a549_k562_recon_perturb_sigs, file.path(PATH, "data/sigs/sciplex/recon/a549_k562_gsva_recon_perturb.rds"))
saveRDS(a549_mcf7_recon_perturb_sigs, file.path(PATH, "data/sigs/sciplex/recon/a549_mcf7_gsva_recon_perturb.rds"))
saveRDS(k562_a549_recon_perturb_sigs, file.path(PATH, "data/sigs/sciplex/recon/k562_a549_gsva_recon_perturb.rds"))
saveRDS(k562_mcf7_recon_perturb_sigs, file.path(PATH, "data/sigs/sciplex/recon/k562_mcf7_gsva_recon_perturb.rds"))
saveRDS(mcf7_a549_recon_perturb_sigs, file.path(PATH, "data/sigs/sciplex/recon/mcf7_a549_gsva_recon_perturb.rds"))
saveRDS(mcf7_k562_recon_perturb_sigs, file.path(PATH, "data/sigs/sciplex/recon/mcf7_k562_gsva_recon_perturb.rds"))
```


