---
title: "GSVA Recontextualization"
author: "Andrew Chen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: 'united'
    toc: true
    toc_depth: 1
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r, echo=FALSE}
library(tidyomics)
library(sigrecon)

PATH <- file.path(Sys.getenv("MLAB"), "projects/brcameta/projects/sig_recon")
DATA_PATH <- file.path(Sys.getenv("CBM"), "otherStudies/perturbational_data/neurips_2023")
do_save <- TRUE
```

# Loading Data

```{r}
neurips_data <- readRDS(file.path(PATH, "data/openproblems/pseudobulk_cleaned.rds"))

# Perturbed + DMSO
b_sce <- neurips_data |> 
  plyranges::filter(cell_type == "B cells") |>
  as.SingleCellExperiment()
t_sce <- neurips_data |>
  plyranges::filter(cell_type == "T cells") |>
  as.SingleCellExperiment()
nk_sce <- neurips_data |>
  plyranges::filter(cell_type == "NK cells") |>
  as.SingleCellExperiment()
myeloid_sce <- neurips_data |>
  plyranges::filter(cell_type == "Myeloid cells") |>
  as.SingleCellExperiment()

# DMSO only
b_dmso_sce <- neurips_data |> 
  plyranges::filter(cell_type == "B cells") |>
  plyranges::filter(sm_name == "Dimethyl Sulfoxide") |>
  as.SingleCellExperiment()
t_dmso_sce <- neurips_data |>
  plyranges::filter(cell_type == "T cells") |>
  plyranges::filter(sm_name == "Dimethyl Sulfoxide") |>
  as.SingleCellExperiment()
nk_dmso_sce <- neurips_data |>
  plyranges::filter(cell_type == "NK cells") |>
  plyranges::filter(sm_name == "Dimethyl Sulfoxide") |>
  as.SingleCellExperiment()
myeloid_dmso_sce <- neurips_data |>
  plyranges::filter(cell_type == "Myeloid cells") |>
  plyranges::filter(sm_name == "Dimethyl Sulfoxide") |>
  as.SingleCellExperiment()

# Load signatures
myeloid_sigs <- lapply(sigrecon::neurips2023.myeloid, function(x) x$up)
nk_sigs <- lapply(sigrecon::neurips2023.nk, function(x) x$up)
t_sigs <- lapply(sigrecon::neurips2023.t, function(x) x$up)
b_sigs <- lapply(sigrecon::neurips2023.b, function(x) x$up)
```


# GSVA
```{r}
b_myeloid_dmso_recon <- gsva_recon(myeloid_dmso_sce, b_sigs)
b_myeloid_recon <- gsva_recon(nk_sce, b_sigs)
b_myeloid_recon <- gsva_recon(t_sce, b_sigs)
```


