---
title: "GSVA Recontextualization"
author: "Andrew Chen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: 'united'
    toc: true
    toc_depth: 1
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r, echo=FALSE}
library(tidyverse)
library(Biobase)
library(sigrecon)
library(SingleCellExperiment)
library(Seurat)
library(reticulate)
library(data.table)
PATH <- file.path(Sys.getenv("MLAB"), "projects/brcameta/projects/sig_recon")
DATA_PATH <- "/restricted/projectnb/gtex/montilab/CBMrepositoryData/GTEX_dbGap/processed_data"
do_save <- TRUE
```

# Loading Data

```{r}
if(do_save) {
  filepaths <- Sys.glob(paste0(DATA_PATH, "/*.rds"))
  gtex_sces <- list()
  for (filepath in filepaths) {
    filename <- basename(filepath)
    tissue_name <- sub("^RNAseq_GTEx_v10_(.*)\\.rds$", "\\1", filename)
    print(paste0("Reading ", tissue_name))
    # 1. Load Data
    expr <- readRDS(filepath)
    if(ncol(expr) < 30) {
      print(paste0("Fewer than 10 samples, skipping ", tissue_name))
      next
    } else {
      gtex_sces[[tissue_name]] <- expr
    }
  }
  saveRDS(gtex_sces, file.path(PATH, "data/gtex/gtex_tissue_sces.rds"))
} else {
  gtex_sces <- readRDS(file.path(PATH, "data/gtex/gtex_tissue_sces.rds"))
}

# Load signatures
load(file.path(PATH, "sigrecon/data/gtex.aging.rda"))
```


# GSVA
```{r}
whole_blood_aging_sig <- gtex.aging$`Whole_Blood`["up"]
blood_recon_sigs <- lapply(names(gtex_sces), function(x) gsva_recon(sce = gtex_sces[[x]],
                                                                    sigs = whole_blood_aging_sig))
names(blood_recon_sigs) <- names(gtex_sces)
saveRDS(blood_recon_sigs, file.path(PATH, "data/sigs/gtex/blood_all_tissue_gsva_recon_continuous.rds"))
```


