---
title: "GSVA Recontextualization Evaluation"
author: "Andrew Chen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: 'united'
    toc: true
    toc_depth: 1
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(sigrecon)
PATH <- file.path(Sys.getenv("MLAB"), "projects/brcameta/projects/sig_recon")
```

# Loading Data
```{r}
# Loading Signatures and Networks
load(file.path(PATH, "sigrecon/data/gtex.aging.rda"))
blood_aging_sig <- list(blood = gtex.aging$`Whole_Blood`$up)
non_blood_tissue_names <- names(gtex.aging)[names(gtex.aging) != "Whole_Blood"]
blood_recon_sigs <- readRDS(file.path(PATH, "data/sigs/gtex/blood_all_tissue_gsva_recon_continuous.rds"))
blood_recon_sigs <- blood_recon_sigs[non_blood_tissue_names]
blood_recon_sigs <- lapply(blood_recon_sigs, function(x) x$up)
# Full length aging signatures of other tissues
non_blood_aging_sigs_full <- lapply(gtex.aging, function(x) x$up_full)
non_blood_aging_sigs_full <- non_blood_aging_sigs_full[non_blood_tissue_names]
non_blood_aging_sigs_top <- lapply(gtex.aging, function(x) x$up)
non_blood_aging_sigs_top <- non_blood_aging_sigs_top[non_blood_tissue_names]
stopifnot(all.equal(names(blood_recon_sigs), names(non_blood_aging_sigs_full)))
stopifnot(all.equal(names(blood_recon_sigs), names(non_blood_aging_sigs_top)))
```

```{r}
# KS Test
blood_ks_obj <- v.ks.test(data_vecs = blood_recon_sigs, ref_vecs = non_blood_aging_sigs_full)
# Jaccard
blood_jacc <- v.jaccard(blood_recon_sigs, non_blood_aging_sigs_top)
# Displacement
seed_sigs <- rep(blood_aging_sig, length(blood_recon_sigs))
names(seed_sigs) <- names(blood_recon_sigs)
blood_displaced <- count_displaced_genes(recon_sig = blood_recon_sigs, seed_sig = seed_sigs)
    
recon_df <- data.frame(
    source = "blood",
    displaced = unname(unlist(lapply(blood_displaced, function(x) x$displaced))),
    kept = unname(unlist(lapply(blood_displaced, function(x) x$not_displaced))),
    pert = names(blood_recon_sigs),
    jacc = blood_jacc,
    k_d = blood_ks_obj$D_stats,
    k_p = blood_ks_obj$p_vals,
    recon = TRUE
)
```

```{r}
# KS Test
blood_ks_obj <- v.ks.test(data_vecs = seed_sigs, ref_vecs = non_blood_aging_sigs_full)

# Jaccard
blood_jacc <- v.jaccard(seed_sigs, non_blood_aging_sigs_top)

# Displacement
blood_displaced <- count_displaced_genes(recon_sig = non_blood_aging_sigs_top, seed_sig = seed_sigs)
    
no_recon_df <- data.frame(
    source = "blood",
    displaced = unname(unlist(lapply(blood_displaced, function(x) x$displaced))),
    kept = unname(unlist(lapply(blood_displaced, function(x) x$not_displaced))),
    pert = names(blood_recon_sigs),
    jacc = blood_jacc,
    k_d = blood_ks_obj$D_stats,
    k_p = blood_ks_obj$p_vals,
    recon = FALSE
)
```

```{r}
combined_aggregated_df <- merge(no_recon_df %>% dplyr::select("source", "pert", "k_d", "jacc"), 
                                recon_df %>% mutate(kept_alpha = kept/(kept+displaced)), 
                                by = c("source", "pert"), 
                                suffixes = c("_FALSE", "_TRUE")) %>% tibble
combined_aggregated_df
```

# blood {.tabset}

## KS
```{r}
combined_aggregated_df %>% 
  filter(source=="blood") %>%
  ggplot(aes(x=k_d_FALSE, y=k_d_TRUE)) +
  geom_point(aes(alpha=kept_alpha)) +
  geom_abline(color="black") +
  scale_alpha_continuous("Proportion of Source Kept") +
  labs(title = paste("KS Distances in", "blood Up"), 
     x = "KS Distance (Before)",
     y = "KS Distance (After)") +
  coord_cartesian(xlim = c(-1, 1), ylim = c(-1, 1))
```

## Jaccard 
```{r}
combined_aggregated_df %>% 
  filter(source=="blood") %>%
  ggplot(aes(x=jacc_FALSE, y=jacc_TRUE)) +
  geom_point(aes(alpha=kept_alpha)) +
  geom_abline(color="black") +
  scale_alpha_continuous("Proportion of Source Kept") +
  labs(title = paste("Jaccard Similarity in", "blood Up"), 
     x = "Jaccard (Before)",
     y = "Jaccard (After)") +
  coord_cartesian(xlim = c(-1, 1), ylim = c(-1, 1))
```

```{r}
combined_aggregated_df %>% 
  dplyr::mutate(k_d_diff = k_d_TRUE - k_d_FALSE,
                jacc_diff = jacc_TRUE - jacc_FALSE) %>% 
  dplyr::arrange(desc(k_d_diff))
```

## Highest k_d_diff
```{r}
aging_full_sig <- non_blood_aging_sigs_full$`Prostate`
blood_ranks <- match(blood_aging_sig$blood, aging_full_sig)
blood_ranks <- blood_ranks[!is.na(blood_ranks)]
sigrecon::kstest(length(aging_full_sig), blood_ranks, plotting = TRUE)
```

```{r}
aging_full_sig <- non_blood_aging_sigs_full$`Prostate`
blood_ranks <- match(blood_recon_sigs$Prostate, aging_full_sig)
blood_ranks <- blood_ranks[!is.na(blood_ranks)]
sigrecon::kstest(length(aging_full_sig), blood_ranks, plotting = TRUE)
```

## Lowest k_d_diff
```{r}
aging_full_sig <- non_blood_aging_sigs_full$`Small_Intestine_Terminal_Ileum`
blood_ranks <- match(blood_aging_sig$blood, aging_full_sig)
blood_ranks <- blood_ranks[!is.na(blood_ranks)]
sigrecon::kstest(length(aging_full_sig), blood_ranks, plotting = TRUE)
```

```{r}
aging_full_sig <- non_blood_aging_sigs_full$`Small_Intestine_Terminal_Ileum`
blood_ranks <- match(blood_recon_sigs$`Small_Intestine_Terminal_Ileum`, aging_full_sig)
blood_ranks <- blood_ranks[!is.na(blood_ranks)]
sigrecon::kstest(length(aging_full_sig), blood_ranks, plotting = TRUE)
```

# Pairwise summary
```{r}
combined_aggregated_df %>%
  mutate(Recon_Succ_Ks = k_d_TRUE > k_d_FALSE + 1e-2,
         Recon_Fail_Ks = k_d_TRUE < k_d_FALSE - 1e-2,
         Recon_Succ_Jacc = jacc_TRUE > jacc_FALSE + 1e-2,
         Recon_Fail_Jacc = jacc_TRUE < jacc_FALSE - 1e-2) %>%
  group_by(source) %>%
  summarize(Recon_Works_Jacc = sum(Recon_Succ_Jacc)/(sum(Recon_Succ_Jacc) + sum(Recon_Fail_Jacc)),
            Recon_Works_KS = sum(Recon_Succ_Ks)/(sum(Recon_Succ_Ks) + sum(Recon_Fail_Ks)),
            Jacc_Wilcox_pval = wilcox.test(jacc_TRUE, jacc_FALSE, paired = TRUE, alternative="greater")$p.value,
            Jacc_t_pval = t.test(jacc_TRUE, jacc_FALSE, paired=TRUE, alternative="greater")$p.value,
            KS_Wilcox_pval = wilcox.test(k_d_TRUE, k_d_FALSE, paired = TRUE, alternative="greater")$p.value,
            KS_t_pval = t.test(k_d_TRUE, k_d_FALSE, paired=TRUE, alternative="greater")$p.value)
```
